### ISSUE TITLE
Evolution of the generations during training

### ISSUE THREAD

**Issue by pabloppp** [VITA-Group/TransGAN#1]
Hello, I was wondering if you had available anywhere some samples of the outputs of the GAN a different stages of training: like before training, after N epochs, etc... To get an idea of how the model is reaching its goal, and what to expect while training to see if I'm way out of the path. I have been trying to make something very similar with limited success, and always have to fall back to some convolutional layers (like putting a Conv2D after every attention layer) to get any relevant results... 

Thanks!

**Comment by yueruchen** [comment]
Good idea! I'll update this soon.

**Comment by pabloppp** [comment]
Just as a little update from my side, I have not managed to make my approach work using most of your techniques, but here is what I get at the beginning:
![image](https://user-images.githubusercontent.com/4237014/108479701-557f5080-7296-11eb-9d93-8ade13946e72.png)
The first 2 are the real 32x32 images, the 2 in the center are the output for the SR loss, and the last 2 the ones generated from noise. As you see the output is very "boxy" and we can clearly appreciate the 8x8 boxes (since the input noise is a sequence of 8x8), and you can also see that while the SR very quickly picks on shape and color since it has the LR image as input, the images generated from noise are very bad and are identical due to mode collapse.

After several epochs, this is what I get 
![image](https://user-images.githubusercontent.com/4237014/108480113-d3435c00-7296-11eb-8143-e60a2868344f.png)
You can see that now the SR images are much less "blocky" and start to be smoother, looking more similar to the input images, but the images generated from noise are still very blocky, don't look like a face at all, and still suffer from mode collapse :( 

Did you find something like that during your training? Any tip or idea on what could be the issue causing this kind of results? Do I just need more iterations?Thanks 🙇

**Comment by yueruchen** [comment]
Hi @pabloppp ,

I think you are very close to the results. If you simply want to reproduce pleasing visual results, I would suggest that you first go without auxiliary SR loss. As we have suggested in our paper, SR loss cost memory and training speed, you can firstly go without it for quick reproducing. Also, I give an `args.patch_size` to indicate how many patches to split in discriminator, I think both `args.patch_size=4` and `args.patch_size=8` should work, you can go with `args.patch_size=4` firstly.

**Comment by pabloppp** [comment]
Hi @yueruchen thank you very much for your feedback!!! I already tried without SR loss with very similar results. I began without it then added it in case it helped. Also, I am already using a patch size of 4 in the discriminator :/ must be something else, I'll keep trying 🙇

**Comment by yueruchen** [comment]
Then it would be just training it longer...

**Comment by yueruchen** [comment]
@pabloppp 
I just upload the checkpoint of celeba64 dataset. check here https://github.com/VITA-Group/TransGAN/blob/master/exps/celeba64_test.sh
