### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mark-Yu1** [VITA-Group/TransGAN#10]
May I ask why the mask is used in the Transformer Encoder? It seems that the original implemention only uses the mask in the Transformer Decoder.Thanks.

**Comment by yueruchen** [comment]
The purpose of the mask is different. The original transformer use the mask for pretraining and text predicting. But here we use mask to force the self-attention module to focus more on the neighborhood pixels. And we only use transformer encoder in our network.

**Comment by Mark-Yu1** [comment]
Now I understand, thank you!

**Comment by Mark-Yu1** [comment]
Hi, I'm trying to train the model  on CelebA64*64. as you said that the mask plays a big role in the training stage, could you please tell me how to set the "is_mask" argument? Also, could you please tell me how to set the "drop","attn_drop" and "drop_path" in the "Block" class when initializing it? Thank you very much!
