### ISSUE TITLE
which one is the cifar10 checkpoint

### ISSUE THREAD

**Issue by lingcong-k** [VITA-Group/TransGAN#11]
As mentioned in title, there seems  no cifar10 checkpoint in the google drive. right?

**Comment by yueruchen** [comment]
Thanks for reminding, I will upload it soon.

**Comment by gmt710** [comment]
Hello, Greatly thanks for your job. If not get the cifar10 pth, Can we train the pth by ourself ?

**Comment by yueruchen** [comment]
check here https://drive.google.com/drive/folders/1UEBGHyuDHqr0VzOE9ePx5kZX0zbLqWLh?usp=sharing
