### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Mark-Yu1** [VITA-Group/TransGAN#12]
Hi, I'm trying to train the model on CelebA64*64. as you said that the mask plays a big role in the training stage, could you please tell me how to set the "is_mask" argument? Also, could you please tell me how to set the "drop","attn_drop" and "drop_path" in the "Block" class when initializing it? Thank you very much!

**Comment by yueruchen** [comment]
I think you can use the default "is_mask" argument in model file, and drop_out ratio is all set to 0.

**Comment by Mark-Yu1** [comment]
Thank you! I will try it.
