### ISSUE TITLE
Can this model generate 128 or 256 resolution images?

### ISSUE THREAD

**Issue by DaddyJin** [VITA-Group/TransGAN#13]
Can this model generate 128 or 256 resolution images? If so, what is the cfg of corresponding situation?
I tried 128 with the parameter "bottom_width" equal to 16  , but single GPU card with 24 GB seems not enough.

**Comment by yueruchen** [comment]
Yes, checkout here https://github.com/VITA-Group/TransGAN/blob/master/exps/celeba_hq_256_train.py
