### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by GaranWu** [VITA-Group/TransGAN#16]
Hello! When will the training code be updated, or how should I write it? Could you please guide me, thank you very much.

**Comment by yueruchen** [comment]
Training code will come soon. You can firstly try to use the model file and our previous work AutoGAN repo https://github.com/VITA-Group/AutoGAN.

**Comment by GaranWu** [comment]
thank you very much !&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VITA-Group/TransGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月17日(星期六) 中午12:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VITA-Group/TransGAN] training code (#16)





 
Training code will come soon. You can firstly try to use the model file and our previous work AutoGAN repo https://github.com/VITA-Group/AutoGAN.
