### ISSUE TITLE
loss 

### ISSUE THREAD

**Issue by Fengww2014** [VITA-Group/TransGAN#18]
can you share the loss curve during training？ i found that the losses do not converge during training.
<img width="711" alt="image" src="https://user-images.githubusercontent.com/30151004/115103500-e74cc680-9f84-11eb-9080-f44e8580edd6.png">

**Comment by yueruchen** [comment]
GAN training is a min-max process so it is natural to see the loss not converge to zero.

**Comment by Fengww2014** [comment]
But i also found the d_loss converges to a certain value, and the generated images are not clear.

**Comment by Fengww2014** [comment]
I found that this gan model is difficult to train, and the results obtained are also fuzzy images. In addition, I found that during training, the d_loss is stable and almost unchanged. can you provide some training tricks for me? 
thanks a lot of.

**Comment by yueruchen** [comment]
My setting is lr:1e-4, adam: 0, 0.99, ema:500k img; update D 4 times and G 1 times, using WGAN-GP loss.
