### ISSUE TITLE
Where is implementation of MT-CT?

### ISSUE THREAD

**Issue by subminu** [VITA-Group/TransGAN#21]
Hello, When I saw the training generator code in `funtions.py`, there was no the part corresponding to the multi-task co-training(`MT-CT`). Did i miss the part of `MT-CT`??

Thanks!

**Comment by yueruchen** [comment]
we have updated our paper and MT-CT is no longer needed now. Training code is updated and new paper is here https://arxiv.org/abs/2102.07074
