### ISSUE TITLE
models_search

### ISSUE THREAD

**Issue by chalure** [VITA-Group/TransGAN#24]
in 'models_search" file, why there don't have "building_blocks_search" ?

**Comment by yueruchen** [comment]
"building_blocks_search" is not needed, I just delete it.

**Comment by chalure** [comment]
how to set "-gen_bs“ and "-dis_bs" ?

**Comment by yueruchen** [comment]
128 and 64 if you don't use gradient accumulation. `--g_accumulated_times` and `--accumulated_times` are set for gradient accumulation.
