### ISSUE TITLE
Linear Unflatten layer

### ISSUE THREAD

**Issue by nthcode** [VITA-Group/TransGAN#25]
As I understand, your paper wants to completely remove convolution layers. But in code, for the linear unflatten layer (to obtain RGB image), I see you use conv2d. Why do you use this? Is there anyway that we can get RGB image without conv2d?

**Comment by Hsintien-Ng** [comment]
Also, the first layer to embed the image to feature in the discriminator is the nn.Conv layer. Could you explain it?

**Comment by Hsintien-Ng** [comment]
I see. The nn.Conv is with kernel_size=patch_size, and the nn.deconv is with kernel_size=1. Both two are equal to the fc layer. Right?

**Comment by yueruchen** [comment]
@nthcode I use Conv2D with kernel_size=1 and stide=1, this is exactly equal to a feed-forward MLP layer.

**Comment by yueruchen** [comment]
@Hsintien-Ng 'The nn.Conv is with kernel_size=patch_size, and the nn.deconv is with kernel_size=1. Both two are equal to the fc layer.' 
yes

**Comment by nthcode** [comment]
@yueruchen, @Hsintien-Ng  Thanks for your explain.
