### ISSUE TITLE
UnboundLocalError: local variable 'gen_net' referenced before assignment

### ISSUE THREAD

**Issue by Mr-AlanLiu** [VITA-Group/TransGAN#29]
excuse me, sorry to disturb you. When I run the train_derived.py, the terminal appeared the "UnboundLocalError: local variable 'gen_net' referenced before assignment".  The sentences of if , elif and else are used too much,  I think.  How can I fix it. Thanks.

**Comment by yueruchen** [comment]
Could you provide the full error message?

**Comment by Mr-AlanLiu** [comment]
![1](https://user-images.githubusercontent.com/31244745/123574648-d29d7200-d802-11eb-9188-c9f252ce5e24.png)

**Comment by Mr-AlanLiu** [comment]
could you give me some advice to solve it

**Comment by yueruchen** [comment]
I think you might change the training script? We use distributed training instead of data parallel

**Comment by wind754203900** [comment]
I meet same problem too. I solve it by declaring the network in "else" field:
gen_net = eval('models_search.' + args.gen_model + '.Generator')(args=args)
dis_net = eval('models_search.' + args.dis_model + '.Discriminator')(args=args)

**Comment by yueruchen** [comment]
@wind754203900 
Did you remove `--multiprocessing_distributed` in the training script?
