### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by maximzubkov** [VITA-Group/TransGAN#3]
Hello!
Thanks for your works on TransGAN, it's amazing! When do you plan to post the training scripts?

**Comment by Harryjun** [comment]
mark

**Comment by jiaxinyu618** [comment]
test.py contains the training code

**Comment by xihaofei** [comment]
> test.py contains the training code

Isn't that  a test file?

**Comment by 925710545** [comment]
mark

**Comment by lucasalavapena** [comment]
> test.py contains the training code

But it says in the readme.md `Coming soon` under https://github.com/VITA-Group/TransGAN#training and the test script requires a trained model path, right?

**Comment by yueruchen** [comment]
Sorry for the late reply. Training code is updated.
