### ISSUE TITLE
Training on single GPU

### ISSUE THREAD

**Issue by thearkaprava** [VITA-Group/TransGAN#30]
What script should I use to train TransGAN (celeba_hq dataset) on a single GPU? I am using a PC with 4GB NVIDIA GTX 1650.

**Comment by yueruchen** [comment]
4GB might not be enough. As we suggested, celeba_hq might need at least 8 V100 GPUs

**Comment by thearkaprava** [comment]
Which dataset can I use for a single GPU? Also, for training which script should I use?

**Comment by yueruchen** [comment]
https://github.com/VITA-Group/TransGAN/blob/master/exps/cifar_train.py

**Comment by thearkaprava** [comment]
So should I run the following script?
`python exps/cifar_train.py`

**Comment by yueruchen** [comment]
Yes

**Comment by victor-szf** [comment]
？？？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yifan ***@***.***>
发送时间: 2021年7月9日 12:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [VITA-Group/TransGAN] Training on single GPU (#30)


Closed #30<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVITA-Group%2FTransGAN%2Fissues%2F30&data=04%7C01%7C%7C7988299d4e594602087c08d9429380f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637614023553196534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BKN1p6SjewmG7zlgfofMgmfN4Gxrp7SY3dThsmedRbk%3D&reserved=0>.

―

**Comment by yueruchen** [comment]
@victor-szf 
run this `python exps/cifar_train.py`

**Comment by yueruchen** [comment]
@thearkaprava @victor-szf 
I just found one bug in the code, could you please pull again?

**Comment by StandardL** [comment]
> 4GB might not be enough. As we suggested, celeba_hq need at least 8 V100 GPUs

@yifanjiang19 
Is it possible to train celeba-hq-256 with single 24GB RTX 3090? We only have 4*RTX 3090, but we can't use them all the time.
