### ISSUE TITLE
Error occurs when training on Cifar-10

### ISSUE THREAD

**Issue by wind754203900** [VITA-Group/TransGAN#31]
Excuse me. I tried to train the transGAN on cifar10 dataset by using the script in "exps/cifar_train.py", but error occurs with `RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 3`  in line `attn = attn + relative_position_bias.unsqueeze(0)` and `real_validity = dis_net(real_imgs)`. 
![截图_2021-06-29_19-22-47](https://user-images.githubusercontent.com/36593904/123789499-cce18280-d90f-11eb-9ca3-ba5f0538684b.png)
 I print the shape of tensor 'attn' and 'relative_position_bias' with (64, 4, 64, 64) and (4, 256, 256) .  I haven't modify the code in discriminator. 
![截图_2021-06-29_19-23-33](https://user-images.githubusercontent.com/36593904/123789515-d1a63680-d90f-11eb-9497-d8b14059ab7a.png)
I don't know how to solve this problem.

**Comment by yueruchen** [comment]
Sorry, I just found the script has some typos. `--patch_size` should be 2 instead of 4. I just commit and you can pull again.

**Comment by wind754203900** [comment]
It works! Thanks!

**Comment by yueruchen** [comment]
@wind754203900 
I just found one bug in the code, could you please pull again?
