### ISSUE TITLE
你好，请问我应该如何复现论文效果，例如cifar10上的效果，如何加载预训练模型？是使用fid stat中的文件么

### ISSUE THREAD

**Issue by ToscanaGoGithub** [VITA-Group/TransGAN#33]
需要复现一下您这篇论文，不知道如何验证模型效果，如何加载预训练模型，十分感谢

**Comment by yueruchen** [comment]
FID stats file is for evaluation, I'll upload checkpoint soon.

**Comment by Nut-Guo** [comment]
> FID stats file is for evaluation, I'll upload checkpoint soon.

I'm trying to reimplement this model in another framework and would be happy if you can provide the checkpoint file so that I can check the correctness of my implementation. Could you please provide this file now?

**Comment by yueruchen** [comment]
@Nut-Guo Can you try this checkpoint with current codebase?
https://drive.google.com/file/d/1Td9baoNua6jNtVvsnJczW1u4QWa1w9sl/view?usp=sharing

**Comment by Nut-Guo** [comment]
> @Nut-Guo Can you try this checkpoint with current codebase?
> https://drive.google.com/file/d/1Td9baoNua6jNtVvsnJczW1u4QWa1w9sl/view?usp=sharing

Thanks! I'll try it.

**Comment by z625715875** [comment]
Hi, @yueruchen 

Could you please provide the celeba checkpoint? Thanks very much.

Best,
Yang
