### ISSUE TITLE
Single GPU running model

### ISSUE THREAD

**Issue by victor-szf** [VITA-Group/TransGAN#35]
Hello, I have a 3080ti. How to modify the code and run it on a GPU?

**Comment by yueruchen** [comment]
You can use gradient accumulation, I already implement it in the code. Just change `--accumualted_times` and `--g_accumulated_times`

**Comment by victor-szf** [comment]
thank you! I have another question, why is my g loss negative?

[Batch 1100/1563] [D loss: 4.573245] [G loss: -47.964233] [ema: 0.993718]    

![1626009353(1)](https://user-images.githubusercontent.com/74765233/125196646-3907a300-e28d-11eb-8565-48389ff23902.jpg)

**Comment by yueruchen** [comment]
It is correct. And I just found one bug in the code, could you please pull again?
