### ISSUE TITLE
Training for CIFAR-10

### ISSUE THREAD

**Issue by Andrew-X-Wang** [VITA-Group/TransGAN#38]
Hello,

I've been having a lot of trouble running the most basic model training for CIFAR-10. Is this the correct usage?

python exps/cifar_train.py

The code appeared to stall, and rerunning a second time resulted in "Address already in use",  and I wasn't able to find options to run for either a single GPU/run without multiprocessing-distributed. I've tried editing cifar_train.py to specify only a single GPU, and otherwise calling torch.cuda.set_device(...), but the training never goes through.

I did have to change the version of tensorboard from requirements.txt, though I don't see how that would result in these issues. Do you have any advice on how to make the training run and complete?

Thank you!

**Comment by asarigun** [comment]
Hi @Andrew-X-Wang ! I have recently re-implemented this exciting paper, and if you're interested, you can look at my implementation [here](https://github.com/asarigun/TransGAN). I tried to implement it much more clear as soon as possible. I hope it will be useful for you!

**Comment by yueruchen** [comment]
Hi @Andrew-X-Wang 
For `Address already in use`, you could check `nvidia-smi` and found the existing program to kill, by using `kill -9 xxx`. Also, you can simply use `pkill python`.
You may also consider change the `--dist-url 'tcp://localhost:14256'` to another port to avoid same address
