### ISSUE TITLE
Question about Output of dimension

### ISSUE THREAD

**Issue by ygjwd12345** [VITA-Group/TransGAN#39]
I try to use a generator in ViT_scale3_local_new_rp.py
But I find the output is a noise like
![image](https://user-images.githubusercontent.com/32895754/126669623-44026195-ed24-41e3-b59b-0ba3e0a4557f.png)
Meanwhile, I also find the dimension of the different stages is different from paper
![image](https://user-images.githubusercontent.com/32895754/126669750-f9947622-3106-47c6-8627-012547eefb1a.png)
Would you mind helping me to solve this problem?

**Comment by yueruchen** [comment]
could you please let me know how do you use this generator and where do you print the dimension?

**Comment by ygjwd12345** [comment]
I use generator defined in  ViT_scale3_local_new_rp.py. Meanwhile, I use 
        self.to_patch_embedding = nn.Sequential(
            Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)', p1=16, p2=16),
            nn.Linear(3*16*16, 128),
        )
as projector.

**Comment by yueruchen** [comment]
I'm not familiar with this einops format and I would like to suggest you to follow the original implementation. The dimension is slightly different from the supplementary as I further improve its performance. I'll change it later.
