### ISSUE TITLE
Checkpoint doesn't match

### ISSUE THREAD

**Issue by anj1** [VITA-Group/TransGAN#4]
Commit 944261520899ea5192b3fd6fdbc8a464ea6589a2 breaks the checkpoint loading:

```
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Unexpected key(s) in state_dict: "module.to_rgb.0.weight", "module.to_rgb.0.bias", "module.to_rgb.0.running_mean", "module.to_rgb.0.running_var", "module.to_rgb.0.num_batches_tracked". 
```

Could you upload the updated checkpoint, thanks.

**Comment by yueruchen** [comment]
Hi @anj1 

Thanks for providing this information!!
I just update the code, the current one should work.

**Comment by anj1** [comment]
Thank you, everything works now, except for opencv not being in requirements.txt.

**Comment by yueruchen** [comment]
Just update it. Thanks!
