### ISSUE TITLE
Question about ViT_custom_local544444_256_rp.py

### ISSUE THREAD

**Issue by RSMung** [VITA-Group/TransGAN#46]
I found that these code maybe duplicate. They are the code in https://github.com/VITA-Group/TransGAN/blob/7449c76508219ccbf32e7a7047304ee6908f85c5/models_search/ViT_custom_local544444_256_rp.py#L383
if self.args.latent_norm:
            latent_size = z.size(-1)
            z = (z/z.norm(dim=-1, keepdim=True) * (latent_size ** 0.5))

**Comment by yueruchen** [comment]
Thanks, you can simply ignore it as it is not used.
