### ISSUE TITLE
FID score

### ISSUE THREAD

**Issue by gl0513** [VITA-Group/TransGAN#49]
why FID score are always nan in CIFAR10?I calculate the FID score for two identical datasets that are also NAN.
![image](https://user-images.githubusercontent.com/49199918/142628452-cfc9cb88-2375-4deb-802b-d2ffbc550a07.png)

![image](https://user-images.githubusercontent.com/49199918/142628556-0526d880-1cf5-43d4-add8-e874a47d7834.png)
![image](https://user-images.githubusercontent.com/49199918/142628763-7035c0ef-07ae-47ec-96cf-85af21156559.png)

**Comment by yueruchen** [comment]
Hi @gl0513 ,

Do you calculate FID by separately launching another `python test.py` process?

**Comment by gl0513** [comment]
No, I calculated FID by cifar_train.py

**Comment by yueruchen** [comment]
I would suggest to use `test.py` instead. But actually, `train.py` should not result nan. Maybe you can try `test.py` again? Just use the checkpoint path on `--load_path`

**Comment by yzhwang** [comment]
@yueruchen Hi! Any updates on this issue? I have cloned the repo and run the cifar_train.py script with vanilla version. And still get the nan error. May I ask what environment you use for your running? For us we run it on A100 GPU and all the py packages from your requirements.txt.

For your suggestion on using test.py, I think it is necessary to include validation of the model. So that we can track the performance of the model. Would you kindly take a look and see if you could reproduce and solve this issue? Thanks a lot!

**Comment by yueruchen** [comment]
Hi @yzhwang , 
I'm unable to reproduce this nan from my side so I would encourage you to run another `test.py`. You still can use it to track the performance during the training process, since `train.py` will save checkpoint every epoch and `test.py` will load checkpoint automatically.

**Comment by yzhwang** [comment]
> Hi @yzhwang , I'm unable to reproduce this nan from my side so I would encourage you to run another `test.py`. You still can use it to track the performance during the training process, since `train.py` will save checkpoint every epoch and `test.py` will load checkpoint automatically.

Thanks Yueru, that is exactly what I'm doing right now.

**Comment by Jamie-Cheung** [comment]
> Hi @yzhwang , I'm unable to reproduce this nan from my side so I would encourage you to run another `test.py`. You still can use it to track the performance during the training process, since `train.py` will save checkpoint every epoch and `test.py` will load checkpoint automatically.

Have your sloved this proplbeM? I face the same problem when I implement another code writed by pytorch.

**Comment by yueruchen** [comment]
Hi @Jamie-Cheung ,

Sorry it is not solved, the best way is still run two separate jobs.
