### ISSUE TITLE
Using Conv?

### ISSUE THREAD

**Issue by john2john3** [VITA-Group/TransGAN#50]
Hello, thank you for uploading the code for your awesome work.

I'm looking at the code and there is a convolutional layer in the generator (self.deconv). Is there some reason using it?
On the paper it says there are no convolutional layers, so I'm a little bit confused

Thank you

**Comment by yueruchen** [comment]
Hi @john2john3,

The deconv layer is actually a 1x1 conv, so it is same to the feed-forward MLP.

**Comment by john2john3** [comment]
Ah ha!

Thank you for your response
