### ISSUE TITLE
Training fails

### ISSUE THREAD

**Issue by anj1** [VITA-Group/TransGAN#7]
I've tried using the function `train` in functions.py, and training seems to fail:

```
  File "functional.py", line 86, in adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: output with shape [768] doesn't match the broadcast shape [3, 48, 1, 768]
``

**Comment by yueruchen** [comment]
It seems that you have modified some code? I don't see `exp_aug` in the code.

**Comment by anj1** [comment]
Ah sorry pasted the wrong part of the error:

```
  File "functions.py", line 190, in train
    gen_optimizer.step()
```

**Comment by yueruchen** [comment]
could you please use this code to adopt optimizer?
```
gen_optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, gen_net.parameters()),
                                        args.g_lr, (args.beta1, args.beta2))
        dis_optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, dis_net.parameters()),
                                        args.d_lr, (args.beta1, args.beta2))
```

**Comment by anj1** [comment]
Hi, I'm using a script similar to test.py which does that by default when using the `adam` optimizer. So that doesn't fix the problem.

**Comment by yueruchen** [comment]
You can first go with AutoGAN framework with our model. That would be much more easier. https://github.com/VITA-Group/AutoGAN

**Comment by anj1** [comment]
I'm specifically interested in the transformer-only approach.

**Comment by yueruchen** [comment]
I mean you can use the training pipeline provided by AutoGAN (like optimizer, lr) and apply our transformer model (just copy the model file). That would lead to the same results.

**Comment by yueruchen** [comment]
Hi @anj1 
I just found that your issue will appear in pytorch version >=1.4, just switch to 1.3.1 or older version will solve it.
