### ISSUE TITLE
ValueError: Invalid backend: ''nccl''

### ISSUE THREAD

**Issue by Jamie-Cheung** [VITA-Group/TransGAN#72]
I try to implement this code on windows and my computer is 2*3090. Can you give some suggestion about how to solve this problem.

**Comment by yueruchen** [comment]
It is possibly related to some environment on windows, which is out of my knowledge.

**Comment by Mautong** [comment]
@Jamie-Cheung > I try to implement this code on windows and my computer is 2*3090. Can you give some suggestion about how to solve this problem.

Excuse me, have you finished this problem? I met this problem, too
