### ISSUE TITLE
About the Patch Splitting Image.

### ISSUE THREAD

**Issue by GajuuzZ** [VITA-Group/TransGAN#82]
Can you explain more about using Conv2d as a patch-splitting image? (in the Discriminator) Since the image will change when applying the Conv and it didn't split the image into parts of a grid as the Vision-Transformer do. And I saw some other implement uses Unfold to split the image.

            self.fRGB_1 = nn.Conv2d(3, embed_dim//4, kernel_size=6, stride=4, padding=1)
            self.fRGB_2 = nn.Conv2d(3, embed_dim//4, kernel_size=10, stride=8, padding=1)
            self.fRGB_3 = nn.Conv2d(3, embed_dim//2, kernel_size=18, stride=16, padding=1)

**Comment by yueruchen** [comment]
My original implementation use the same kernel_size and stride while in that case this is equal to splitting. But latter I found that overlapped splitting get slightly better performance and I changed to this version. But you can still change it back to non-overlapped version and that will give you reasonable results as well.

**Comment by GajuuzZ** [comment]
I don't understand how convolution will split the image? since it convolves the whole image and gets the new one for each channel.
And yes, when plotting it didn't seem to have a reasonable result.

**Comment by yueruchen** [comment]
Convolution is not equal to splitting but equals to splitting + additional MLP layers
