### ISSUE TITLE
Some question about loss

### ISSUE THREAD

**Issue by JUSTM0VE0N** [VITA-Group/TransGAN#84]
Hello, I would like to ask if this situation is normal.
![QQ图片20230308221530](https://user-images.githubusercontent.com/121370263/223737213-be92a881-3bb6-4195-aedb-cc5baf885533.png)
![QQ图片20230308221542](https://user-images.githubusercontent.com/121370263/223737258-3f535728-d35e-47a7-8147-5bede2c370c2.png)

**Comment by yifanjiang19** [comment]
I dont remember so clearly after a very long time. I would suggest you to test the FID after every epoch and see if it keep descending.
