### ISSUE TITLE
About the role of function “get_attn_mask”.

### ISSUE THREAD

**Issue by NNNNAI** [VITA-Group/TransGAN#9]
Thanks for your work！

When I'm looking at the code of model/Celeba64_TransGAN.py , I notice that the function “get_attn_mask”  seems to play a role in the training process.Can you point out the specific role of this function?

Thank you~~

**Comment by yueruchen** [comment]
This is used for local initialization. As we have pointed out in our paper, gradually enlarging the window size of this mask can help improve the performance. It will firstly only allow each pixel to interact with the neighborhood pixels and then the full images.

**Comment by NNNNAI** [comment]
Thanks for your answer~, it really solves my doubts.

**Comment by NNNNAI** [comment]
BTW，I have run the test script of STL10 .And I noticed that a lot of the generated graphs have black edges.

![1](https://user-images.githubusercontent.com/30747212/109422223-9bb27d80-7a15-11eb-8e4f-31f37b27abef.png)
![2](https://user-images.githubusercontent.com/30747212/109422226-9d7c4100-7a15-11eb-85b9-4e103e60850a.png)

Is these normal?


>

**Comment by yueruchen** [comment]
This is because the stl-10 dataset itself contains the black boundary. You can check here https://cs.stanford.edu/~acoates/stl10/
![image](https://user-images.githubusercontent.com/14892792/109431262-389bf900-79cb-11eb-966f-94b3dfd6cb59.png)

**Comment by NNNNAI** [comment]
Thanks~
